[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"  # Adjust to your preferred Solidity version

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASE_API_KEY}" }  # Add your Base API key later for verification

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
